version: '3'

services:
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        volumes:
            - zookeeper-data:/tmp/zookeeper
        ports:
            - 2181:2181
        expose:
            - 2181
        networks:
            - pipeline-net
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000

    kafka:
        image: confluentinc/cp-kafka:latest
        volumes:
            - kafka-data:/tmp/kafka-logs
        ports:
            - 9092:9092
            - 9093:9093
        expose:
            - 9092
        networks:
            - pipeline-net
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            KAFKA_LISTENERS: INSIDE://:9093,OUTSIDE://:9092
            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        depends_on:
            - zookeeper

    jobmanager:
        image: flink:1.8.3-scala_2.11
        expose:
            - "6123"
        ports:
            - "8081:8081"
        expose:
            - 8081
        networks:
            - pipeline-net
        command: jobmanager
        environment:
            TZ: Europe/Istanbul
            JOB_MANAGER_RPC_ADDRESS: jobmanager

    taskmanager:
        image: flink:1.8.3-scala_2.11
        expose:
            - "6121"
            - "6122"
        networks:
            - pipeline-net
        depends_on:
            - jobmanager
        command: taskmanager
        links:
            - "jobmanager:jobmanager"
        environment:
            TZ: Europe/Istanbul
            JOB_MANAGER_RPC_ADDRESS: jobmanager

    datasource:
        build:
            context: ./datasource
            dockerfile: Dockerfile
        networks:
            - pipeline-net
        ports:
            - "4567:4567"
        expose:
            - 4567
        environment:
            TZ: Europe/Istanbul
            KAFKA_BROKER: kafka:9093
            KAFKA_TOPIC: Events

    master:
        build:
            context: ./master
            dockerfile: Dockerfile
        networks:
            - pipeline-net
        ports:
            - "4568:4568"
        expose:
            - 4568
        environment:
            TZ: Europe/Istanbul
            KAFKA_BROKER: kafka:9093
            KAFKA_EVENTS_TOPIC: Events
            KAFKA_ACTIONS_TOPIC: Actions
            FLINK_BASE_API: http://jobmanager:8081
        depends_on:
            - jobmanager
            - taskmanager
            - kafka

    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        volumes:
            - './client:/app'
            - '/app/node_modules'
        ports:
            - '3000:80'
        expose:
            - 3000

    executor:
        build:
            context: ./executor
            dockerfile: Dockerfile
        networks:
            - pipeline-net
        environment:
            KAFKA_BROKER: kafka:9093
            KAFKA_TOPIC: Actions


volumes:
    zookeeper-data:
    kafka-data:

networks:
    pipeline-net:
        driver: bridge
